// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQKwS0-RCV7iDz5D9J_XFkg9AYisT_McI',
    appId: '1:63769687135:web:3f313715a09250289ed7ea',
    messagingSenderId: '63769687135',
    projectId: 'kutuphaneotomasyon-1151e',
    authDomain: 'kutuphaneotomasyon-1151e.firebaseapp.com',
    storageBucket: 'kutuphaneotomasyon-1151e.appspot.com',
    measurementId: 'G-Q8RFKT6MV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY_8Hd-eWckMzTP3CEJmOVUJ-nKuVSiUw',
    appId: '1:63769687135:android:cd6781af817ee37d9ed7ea',
    messagingSenderId: '63769687135',
    projectId: 'kutuphaneotomasyon-1151e',
    storageBucket: 'kutuphaneotomasyon-1151e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcRIo1NDnnWdyX00Foc8PCFLuIbWKiVw0',
    appId: '1:63769687135:ios:e32665d1f90037629ed7ea',
    messagingSenderId: '63769687135',
    projectId: 'kutuphaneotomasyon-1151e',
    storageBucket: 'kutuphaneotomasyon-1151e.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcRIo1NDnnWdyX00Foc8PCFLuIbWKiVw0',
    appId: '1:63769687135:ios:85ebcd8934fbaaef9ed7ea',
    messagingSenderId: '63769687135',
    projectId: 'kutuphaneotomasyon-1151e',
    storageBucket: 'kutuphaneotomasyon-1151e.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyon.RunnerTests',
  );
}
